title : Ben's Blog
tagline: Blog Tagline
author :
  name : Yujie Du
  email : duyujie.dyj@gmail.com
  github : YujieDu
  twitter : ben_duyujie
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
